### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by SquidDev**
If you'd like me to split this into separate branches I'm happy to.
 - Cleaned up some code.
 - Basic validation for symbols: `(def (+ 2 3) 5)` is now invalid.
 - Use `{type: 'variable', name: 'whatever'}` for variable access. Should be easier for me to track variable usage now.
 - Inline statements (I haven't done `switch` yet as it looks a bit daunting :smile:).
 - Fix macros on nested expressions: `partial (lambda (x y) (^^ x y)) 2)` was broken before.

```clojure
(let (a (if a b c)) a)
```
becomes
```lua
local __temp
if a then __temp = b else __temp = c end
local a = __temp
```
rather than
```lua
local a = (function() if a then return b else return c end)(table.unpack(args or {}))
```
I have to use a temp variable to prevent hiding variables inherited from parent scopes. Hopefully will be able to remove this verbosity once I implement the optimization code.

I've also changed `id` back to being a function as tests were failing. IMHO it should be a function anyway as you are more likely to pass it as an argument then call it explicitly.

### CODE REVIEW

**Comment by SquidDev** [comment]
Don't merge yet, I've got a couple more things to add.

**Comment by SquidDev** [comment]
There are still some bugs with if statements which I'll fix in a bit. Sorryu.

**Comment by demhydraz** [comment]
I'll wait til' the if statements are sorted out, then. `cond` is _very_ complicated (like, I don't even know where to start explaining it) so don't bother. Thanks again!

**Comment by SquidDev** [comment]
Many force pushes later everything appears to work. Scoped blocks are wrapped correctly when passed as arguments and unused "primitive" expressions are discarded if they are not the last expression in the block.

```clojure
(do 2 2)
```
becomes
```lua
do
  return 2
end
```
instead of 
```lua
do
  2;
  return 2
end

**Comment by demhydraz** [comment]
Alright, looks good.

**Pull request merged**
